//
//  TodayClients.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB
@objcMembers

class TodayClients: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _createdAt: NSNumber?
    var _clientName: String?
    var _clientPhotoURL: String?
    
    class func dynamoDBTableName() -> String {

        return "birdee-mobilehub-1340061840-todayClients"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_createdAt"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_createdAt" : "createdAt",
               "_clientName" : "clientName",
               "_clientPhotoURL" : "clientPhotoURL",
        ]
    }
}
